/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Mesto;
import domen.NadleznoLice;
import domen.OpstiDomenskiObjekat;
import domen.Student;
import java.awt.BorderLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.KomunikacijaKlijent;
import table.model.StudentTableModel;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;
import util.Util;

/**
 *
 * @author student1
 */
public class FrmUnosStudenta extends javax.swing.JFrame{
    private final DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
    static NadleznoLice nlc;
    /**
     * Creates new form FrmUnosPartnera
     */
    public FrmUnosStudenta(NadleznoLice nlc) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        srediFormu();
        this.nlc = nlc;
        this.setTitle("FRMUNOS");
        //ProbniFrejm pf = new ProbniFrejm(); pf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtBrIndeksa = new javax.swing.JTextField();
        jIme = new javax.swing.JLabel();
        jtxtIme = new javax.swing.JTextField();
        jPrezime = new javax.swing.JLabel();
        jtxtPrezime = new javax.swing.JTextField();
        jtxtJMBG = new javax.swing.JTextField();
        jJMBG = new javax.swing.JLabel();
        jtxtKontakt = new javax.swing.JTextField();
        jKontakt = new javax.swing.JLabel();
        jMail = new javax.swing.JLabel();
        jtxtMail = new javax.swing.JTextField();
        jUlica = new javax.swing.JLabel();
        jtxtUlica = new javax.swing.JTextField();
        jMesto = new javax.swing.JLabel();
        jcbMesto = new javax.swing.JComboBox();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jBroj = new javax.swing.JLabel();
        jtxtBroj = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jGodina = new javax.swing.JTextField();
        jSmer = new javax.swing.JTextField();
        jbtnObrisi = new javax.swing.JButton();
        jUnesi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Student ID:");

        jLabel2.setText("Broj indeksa:");

        jIme.setText("Ime:");

        jPrezime.setText("Prezime:");

        jJMBG.setText("JMBG:");

        jKontakt.setText("Kontakt:");

        jMail.setText("Mail:");

        jUlica.setText("Ulica:");

        jMesto.setText("Mesto:");

        jcbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnSacuvaj.setText("Sačuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.setMaximumSize(new java.awt.Dimension(95, 35));
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        jBroj.setText("Broj:");

        jLabel3.setText("Godina:");

        jLabel4.setText("Smer:");

        jbtnObrisi.setText("OBRISI!");
        jbtnObrisi.setMaximumSize(new java.awt.Dimension(95, 35));
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jUnesi.setText("Unesi ocenu");
        jUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnesiActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("  Automatski se možete log-outovati \n             izlaskom iz programa\n       Klikom na dugme dole, možete \n pretražiti studente, brisati i menjati");
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 255));
        jButton2.setText("Pretraži!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jbtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMail)
                            .addComponent(jKontakt)
                            .addComponent(jUlica)
                            .addComponent(jBroj)
                            .addComponent(jMesto))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jIme)
                            .addComponent(jPrezime)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jJMBG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSmer, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                            .addComponent(jGodina)
                            .addComponent(jtxtPrezime)
                            .addComponent(jtxtIme)
                            .addComponent(jtxtJMBG)
                            .addComponent(jtxtBrIndeksa))))
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1))
                            .addComponent(jtxtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIme)
                            .addComponent(jtxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrezime)
                            .addComponent(jtxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jSmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jJMBG)
                            .addComponent(jtxtJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jKontakt)
                            .addComponent(jtxtKontakt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMail)
                            .addComponent(jtxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUlica)
                            .addComponent(jtxtUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBroj)
                            .addComponent(jtxtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMesto)
                            .addComponent(jcbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnSacuvaj)
                            .addComponent(jbtnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUnesi)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
            try {
                int studentID = Integer.parseInt(jtxtStudentID.getText().trim());
                String brIndeksa = jtxtBrIndeksa.getText().trim();
                String ime = jtxtIme.getText().trim();
                String prezime = jtxtPrezime.getText().trim();
                int godina = Integer.parseInt(jGodina.getText().trim());
                String smer = jSmer.getText();
                int JMBG = Integer.parseInt(jtxtJMBG.getText().trim());
                String kontakt = jtxtKontakt.getText().trim();
                String mejl = jtxtMail.getText().trim();
                String ulica = jtxtUlica.getText().trim();
                String broj = jtxtBroj.getText().trim();
                Mesto mesto = (Mesto) jcbMesto.getSelectedItem();
                System.out.println("ID MU JE"+mesto.getId());
                
                Student s = new Student(studentID, brIndeksa, ime, prezime, godina, smer, JMBG, kontakt, mejl, ulica, broj,mesto,nlc);
                //System.out.println("Salje se student , mesto - "+mesto.getNaziv()+", nlc: "+nlc.getIme());
                TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
                toZahtev.setOperacija(Konstante.SACUVAJ_STUDENTA);
                toZahtev.setParametar(s);
                
                KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
                
                TransferObjekatOdgovor toOdgovor = KomunikacijaKlijent.getInstance().primiOdgovor();
                System.out.println("Poruka: "+toOdgovor.getPoruka());
                if (toOdgovor.getIzuzetak() == null) {
                    System.out.println("nakon ovoga slijedi poruka?");
                    JOptionPane.showMessageDialog(this, "Partner je sacuvan!");
//                    for(Observer o : FormeKontroler.getInstance().getObserveri()){
//                        o.osveziPrikaz();
//                        System.out.println("isao metodu osvezi prikaz za broj observera:"+
//                                FormeKontroler.getInstance().getObserveri().size());
//                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Neuspesno cuvanje: "+toOdgovor.getPoruka());
                }
                
            } catch (Exception ex) {
                 Logger.getLogger(FrmUnosStudenta.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
                int studentID = Integer.parseInt(jtxtStudentID.getText().trim());
                String brIndeksa = jtxtBrIndeksa.getText().trim();
                String ime = jtxtIme.getText().trim();
                String prezime = jtxtPrezime.getText().trim();
                int godina = Integer.parseInt(jGodina.getText().trim());
                String smer = jSmer.getText();
                int JMBG = Integer.parseInt(jtxtJMBG.getText().trim());
                String kontakt = jtxtKontakt.getText().trim();
                String mejl = jtxtMail.getText().trim();
                String ulica = jtxtUlica.getText().trim();
                String broj = jtxtBroj.getText().trim();
                Mesto mesto = (Mesto) jcbMesto.getSelectedItem();
                
                Student s = new Student(studentID, brIndeksa, ime, prezime, godina, smer, JMBG, kontakt, mejl, ulica, broj, mesto);
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.OBRISI_STUDENTA);
            toZahtev.setParametar(s);
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
            
            TransferObjekatOdgovor odgovor = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            odgovor.getPoruka();
            JOptionPane.showMessageDialog(this, ime+" "+prezime+" je uspesno obrisan!");
            OpstiDomenskiObjekat n = (OpstiDomenskiObjekat)odgovor.getRezultat();
        } catch (Exception ex) {
            System.out.println("Neuspesno brisanje!");
            Logger.getLogger(FrmUnosStudenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
         int studentID = Integer.parseInt(jtxtStudentID.getText().trim());
         String brIndeksa = jtxtBrIndeksa.getText().trim();
         String ime = jtxtIme.getText().trim();
         String prezime = jtxtPrezime.getText().trim();
         int godina = Integer.parseInt(jGodina.getText().trim());
         String smer = jSmer.getText();
         int JMBG = Integer.parseInt(jtxtJMBG.getText().trim());
         String kontakt = jtxtKontakt.getText().trim();
         String mejl = jtxtMail.getText().trim();
         String ulica = jtxtUlica.getText().trim();
         String broj = jtxtBroj.getText().trim();
         Mesto mesto = (Mesto) jcbMesto.getSelectedItem();
                
                Student s = new Student(studentID, brIndeksa, ime, prezime, godina, smer, JMBG, kontakt, mejl, ulica, broj, mesto);
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.IZMENI_STUDENTA);
            toZahtev.setParametar(s);
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
            
            TransferObjekatOdgovor odgovor = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            
            OpstiDomenskiObjekat n = (OpstiDomenskiObjekat)odgovor.getRezultat();
        } catch (Exception ex) {
            System.out.println("Neuspesno brisanje!");
            Logger.getLogger(FrmUnosStudenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnesiActionPerformed

        int studentID = Integer.parseInt(jtxtStudentID.getText().trim());
        String brIndeksa = jtxtBrIndeksa.getText().trim();
        String ime = jtxtIme.getText().trim();
         String prezime = jtxtPrezime.getText().trim();
         int godina = Integer.parseInt(jGodina.getText().trim());
         String smer = jSmer.getText();
         int JMBG = Integer.parseInt(jtxtJMBG.getText().trim());
         String kontakt = jtxtKontakt.getText().trim();
         String mejl = jtxtMail.getText().trim();
         String ulica = jtxtUlica.getText().trim();
         String broj = jtxtBroj.getText().trim();
         Mesto mesto = (Mesto) jcbMesto.getSelectedItem();
                
        
        Student s = new Student(studentID, brIndeksa, ime, prezime, godina, smer, JMBG, kontakt, mejl, ulica, broj,mesto,nlc);
        
        JDialog dialog = new JDialog(this, "Unos ocene", false);
        
        this.setTitle("Naslov");
        dialog.setLayout(new BorderLayout());
        dialog.add(new UnosOcene(s), BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
        
        
    }//GEN-LAST:event_jUnesiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUnosStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUnosStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUnosStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUnosStudenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUnosStudenta(nlc).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBroj;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jGodina;
    private javax.swing.JLabel jIme;
    private javax.swing.JLabel jJMBG;
    private javax.swing.JLabel jKontakt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jMail;
    private javax.swing.JLabel jMesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPrezime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSmer;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jUlica;
    private javax.swing.JButton jUnesi;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbMesto;
    private javax.swing.JTextField jtxtBrIndeksa;
    private javax.swing.JTextField jtxtBroj;
    private javax.swing.JTextField jtxtIme;
    private javax.swing.JTextField jtxtJMBG;
    private javax.swing.JTextField jtxtKontakt;
    private javax.swing.JTextField jtxtMail;
    private javax.swing.JTextField jtxtPrezime;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtUlica;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        try {
            jUnesi.setVisible(false);
            jbtnIzmeni.setVisible(false);
            jbtnObrisi.setVisible(false);
            // List<Mesto> lm = Kontroler.getInstance().vratiMesta();
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.VRATI_MESTA);
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
            TransferObjekatOdgovor toOdgovor = KomunikacijaKlijent.getInstance().primiOdgovor();
            System.out.println("Metoda: "+ toOdgovor.getPoruka());
            if (toOdgovor.getIzuzetak() != null) {
                System.out.println("Bacio izuzetak");
                throw (Exception) toOdgovor.getIzuzetak();
            }
            List<Mesto> lm = (List<Mesto>) toOdgovor.getRezultat();
            //JComboBox jcbMestoTabela = new JComboBox();
            jcbMesto.removeAllItems();
            for (Mesto m : lm) {
                jcbMesto.addItem(m);
                System.out.println("Mesto id je: "+m.getNaziv());
               //jcbMestoTabela.addItem(m);
            }
            
//          TableColumn tcMesto = jtblPartner.getColumnModel().getColumn(8);
//          tcMesto.setCellEditor(new DefaultCellEditor(jcbMestoTabela));
            
            Student s = (Student) Util.getInstance().get("izabrani_student");
            if (s != null) {
                jUnesi.setVisible(false);
                jbtnIzmeni.setVisible(false);
                jbtnObrisi.setVisible(false);
                System.out.println("jmbg mu je"+s.getJMBG());
                // Operacija je izmena
                jbtnSacuvaj.setVisible(false);
                jtxtStudentID.setText(String.valueOf(s.getStudentID()));
                jtxtStudentID.setEditable(false);
                jtxtBrIndeksa.setText(s.getBrIndeksa());
                jtxtIme.setText(s.getIme());
                jtxtPrezime.setText(s.getPrezime());
                jGodina.setText(String.valueOf(s.getGodina()));
                jSmer.setText(s.getSmer());
                jtxtJMBG.setText(String.valueOf(s.getJMBG()));
                
                
                jtxtKontakt.setText(s.getKontakt());
                jtxtMail.setText(s.getMail());
                jtxtUlica.setText(s.getUlica());
                jtxtBroj.setText(s.getBroj());
                jcbMesto.setSelectedItem(s.getM());
                
                Util.getInstance().remove("izabrani_student");
                
            } else {
                // Operacija je unos
                jbtnIzmeni.setVisible(false);
                jbtnObrisi.setVisible(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage()+" ovde");
        }
    }
}
