/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import domen.Student;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import komunikacija.KomunikacijaKlijent;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Radomir
 */
public class LoginFormaStudent extends javax.swing.JPanel {

    /**
     * Creates new form LoginFormaStudent
     */
    public LoginFormaStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtBrIndeksa = new javax.swing.JTextField();
        jtxtSifra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Broj indeksa:");

        jLabel2.setText("Šifra:");

        jButton1.setText("Loguj se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(61, 61, 61)
                                .addComponent(jtxtSifra))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String brIndeksa = jtxtBrIndeksa.getText().trim();
        String sifra = jtxtSifra.getText().trim();
        
        try {
            
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.VRATI_STUDENTA_LOGIN);
            Student ss = new Student();
            ss.setBrIndeksa(brIndeksa);
            ss.setSifra(sifra);
            toZahtev.setParametar(ss);
            
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
            
            TransferObjekatOdgovor odgovor = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            Student s = (Student) odgovor.getRezultat();
            
//            for(OpstiDomenskiObjekat o : Kontroler.getInstance().vratiStudente()){
//                System.out.println(((Student)o).getIme());
                if(s!=null){
                    JOptionPane.showMessageDialog(this, "Ulogovani ste pod imenom :"+s.getIme()+" "+s.getPrezime());
                    
                   //PrijavaPredmetaZaSlusanjePanel ppzs = new PrijavaPredmetaZaSlusanjePanel(s);
                   PrijavaIspita ppzs = new PrijavaIspita(s);
         JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
        dialog.dispose();
        this.setVisible(false);
        
        ppzs.setVisible(true);
        
        dialog.setLayout(new BorderLayout());
        dialog.add(ppzs, BorderLayout.CENTER);
        dialog.pack();
        dialog.setVisible(true);
                    
                    
                    
                    
//                    super.add(ppzs);
//                    super.remove(this);
                    //this.setVisible(false);
                    
                    return;
                }
//            }
                else
            JOptionPane.showMessageDialog(this, "ILI NE?");
       } catch (Exception ex) {
            Logger.getLogger(LoginFormaStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtxtBrIndeksa;
    private javax.swing.JTextField jtxtSifra;
    // End of variables declaration//GEN-END:variables
}
