/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.OpstiDomenskiObjekat;
import domen.Predmet;
import domen.Student;
import domen.StudentPredmet;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import komunikacija.KomunikacijaKlijent;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konstante;

/**
 *
 * @author Radomir
 */
public class PrijavaPredmetaZaSlusanjePanel extends javax.swing.JPanel {
    int broj = 0;
    Student s;
    /**
     * Creates new form PrijavaPredmetaZaSlusanjePanel
     */
    public PrijavaPredmetaZaSlusanjePanel(Student s) {
        this.s = s;
        initComponents();
        pripremiPanelGodina();
        pripremiPanelPredmetiPoGodini();
        pripremiPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPrijaviPredmet = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboGodina = new javax.swing.JComboBox();
        jComboPredmet = new javax.swing.JComboBox();
        jComboPrijavljeni = new javax.swing.JComboBox();
        jComboNeprijavljeni = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBrojESPB = new javax.swing.JLabel();

        jPrijaviPredmet.setText("Prijavi");
        jPrijaviPredmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrijaviPredmetActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboGodina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboGodina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboGodinaItemStateChanged(evt);
            }
        });
        jComboGodina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGodinaActionPerformed(evt);
            }
        });
        jComboGodina.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboGodinaPropertyChange(evt);
            }
        });

        jComboPredmet.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboPrijavljeni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboNeprijavljeni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Zameni");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Broj trenutno prijavljenih ESPB poena:");

        jBrojESPB.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboGodina, 0, 263, Short.MAX_VALUE)
                .addGap(249, 249, 249))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboPrijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jComboNeprijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPrijaviPredmet)))
                            .addGap(154, 154, 154)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jBrojESPB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboPredmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jPrijaviPredmet))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBrojESPB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboPrijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboNeprijavljeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPrijaviPredmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrijaviPredmetActionPerformed
        Predmet p = (Predmet)jComboPredmet.getSelectedItem();
        System.out.println("Izabran : "+p.getPredmetID());
        
        StudentPredmet sp = new StudentPredmet(s,p);
        
        try {
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.SACUVAJ_PREDMET);
            toZahtev.setParametar(sp);
            
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
            
            TransferObjekatOdgovor odgovor = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            String poruka = (String) odgovor.getPoruka();
            
            if(poruka.equals("Predmet je uspesno sacuvan.")){
            Object[] options = {"NE",
                                "DA"};
                int odg = JOptionPane.showOptionDialog(this,
                "Uspesno ste uneli novi predmet za slusanje! Zelite li da nastavite sa radom?",
                "Izlazak",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,     //do not use a custom Icon
                options,  //the titles of buttons
                options[0]);
                if (odg == JOptionPane.YES_OPTION){
                    SwingUtilities.getWindowAncestor(this).dispose();
                }else{
                    pripremiPanel();
                }
            }
            else JOptionPane.showMessageDialog(this, odgovor.getIzuzetak().toString());
            
        } catch (Exception ex) {
            Logger.getLogger(PrijavaPredmetaZaSlusanjePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPrijaviPredmetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pripremiPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboGodinaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboGodinaItemStateChanged
       
    }//GEN-LAST:event_jComboGodinaItemStateChanged

    private void jComboGodinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGodinaActionPerformed
        //pripremiPanelPredmetiPoGodini();
    }//GEN-LAST:event_jComboGodinaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StudentPredmet izabrani = (StudentPredmet)jComboPrijavljeni.getSelectedItem();
        
        Predmet zamena = (Predmet)jComboNeprijavljeni.getSelectedItem();
        
        izabrani.setPrivremeni(zamena);
       
        
        
        try {
            //zamena
            //Kontroler.getInstance().izmeniPredmet( ((Predmet)jComboNeprijavljeni.getSelectedItem()) );
            
            TransferObjekatZahtev toZahtev = new TransferObjekatZahtev();
            toZahtev.setOperacija(Konstante.IZMENI_PREDMET);
            toZahtev.setParametar(izabrani);
            
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev);
            
            TransferObjekatOdgovor odgovor = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            
        } catch (Exception ex) {
            Logger.getLogger(PrijavaPredmetaZaSlusanjePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboGodinaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboGodinaPropertyChange
        pripremiPanelPredmetiPoGodini();
    }//GEN-LAST:event_jComboGodinaPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBrojESPB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboGodina;
    private javax.swing.JComboBox jComboNeprijavljeni;
    private javax.swing.JComboBox jComboPredmet;
    private javax.swing.JComboBox jComboPrijavljeni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jPrijaviPredmet;
    // End of variables declaration//GEN-END:variables
    private void pripremiPanel() {
        broj=0;
        jComboPrijavljeni.removeAllItems();
        jComboNeprijavljeni.removeAllItems();
        jComboPredmet.removeAllItems();

        pripremiPanelPredmetiPoGodini();
        
        try {
            
            TransferObjekatZahtev toZahtev1 = new TransferObjekatZahtev();
            toZahtev1.setOperacija(Konstante.VRATI_IZ_KOLEKCIJE_PREDMETE);
            
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev1);
            
            TransferObjekatOdgovor odgovor1 = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            
            List<OpstiDomenskiObjekat> predmetiIzKolekcije = (List<OpstiDomenskiObjekat>)odgovor1.getRezultat();
            
            
            TransferObjekatZahtev toZahtev2 = new TransferObjekatZahtev();
            toZahtev2.setOperacija(Konstante.VRATI_PREDMETE);
            toZahtev2.setParametar(s);
            
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev2);
            
            TransferObjekatOdgovor odgovor2 = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            
            List<OpstiDomenskiObjekat> mojiPredmeti = (List<OpstiDomenskiObjekat>)odgovor2.getRezultat();
            
            
            for(OpstiDomenskiObjekat p:mojiPredmeti){
                broj+=(((StudentPredmet)p).getP()).getBrojESPB();
                jComboPrijavljeni.addItem((StudentPredmet)p);
                    for(OpstiDomenskiObjekat o : predmetiIzKolekcije){
                    if(!(((StudentPredmet)p).getP()).getNazivPredmeta().equals((((Predmet)o)).getNazivPredmeta()))
                    {
                        jComboNeprijavljeni.addItem(((Predmet)o));
                    }
                }
            }
            jBrojESPB.setText(broj+"");
        } catch (Exception ex) {
            Logger.getLogger(PrijavaPredmetaZaSlusanjePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void pripremiPanelGodina(){
        jComboGodina.removeAllItems();
        jComboPredmet.removeAllItems();
        
        jComboPrijavljeni.removeAllItems();
        jComboNeprijavljeni.removeAllItems();
        for (int i=1;i<5;i++) {
            jComboGodina.addItem(i);
        }
    }
    private void pripremiPanelPredmetiPoGodini(){
        try {
            jComboPredmet.removeAllItems();
            
            
            
            TransferObjekatZahtev toZahtev1 = new TransferObjekatZahtev();
            toZahtev1.setOperacija(Konstante.VRATI_IZ_KOLEKCIJE_PREDMETE);
            KomunikacijaKlijent.getInstance().posaljiZahtev(toZahtev1);
            TransferObjekatOdgovor odgovor1 = (TransferObjekatOdgovor) KomunikacijaKlijent.getInstance().primiOdgovor();
            
            List<OpstiDomenskiObjekat> predmetiIzKolekcije = (List<OpstiDomenskiObjekat>)odgovor1.getRezultat();
            
            
            for(OpstiDomenskiObjekat ob : predmetiIzKolekcije){
                jComboPredmet.addItem((Predmet)ob);
            }
        } catch (IOException ex) {
            Logger.getLogger(PrijavaPredmetaZaSlusanjePanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrijavaPredmetaZaSlusanjePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

}
